name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # 当代码推送到 main 分支时触发

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # 解决 Node.js 20 弃用警告
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v2
        # 该 Action 会自动执行 npm install && npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
